blog/urls.py
from django.urls import path
from django.contrib import admin
from blog.views import BlogListView, BlogCreateView, BlogDetailView, BlogUpdateView, BlogDeleteView
from blog.apps import BlogConfig
app_name = BlogConfig.name

urlpatterns = [
    path('create/', BlogCreateView.as_view(), name='create'),
    path('', BlogListView.as_view(), name='blog'),
    path('view/<int:pk>/', BlogDetailView.as_view(), name='view'),
    path('edit/<int:pk>/', BlogUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='delete'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('catalog.urls', namespace='catalog')),
                  path('blog/', include('blog.urls', namespace='blog')),
                  path('users/', include('users.urls', namespace='users')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

# Create your models here.

NULLABLE = {'blank': True, 'null': True}

class Post(models.Model):
    title = models.CharField(max_length=100, verbose_name='Заголовок')
    slug = models.CharField(max_length=100, **NULLABLE, verbose_name='Slug')
    description = models.TextField(**NULLABLE, verbose_name='Содержимое')
    image = models.ImageField(upload_to='product/', **NULLABLE, verbose_name='Изображение(превью)')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    is_published = models.BooleanField(default=True, verbose_name='Опубликовано')
    views_count = models.IntegerField(default=0, verbose_name='просмотров')

    def __str__(self):
        return f'{self.title}, {self.slug}'

    class Meta:
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

blog/views.py
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView
from pytils.translit import slugify
from blog.models import Post

# Create your views here.

class BlogCreateView(CreateView):
    model = Post
    fields = ('title', 'description', 'image', 'is_published')
    success_url = reverse_lazy('blog:blog')
    template_name = 'blog/post_list.html'
    extra_context = {
        'title': 'Create Post'
    }

    def form_valid(self, form):
        if form.is_valid():
            new_mat = form.save()
            new_mat.slug = slugify(new_mat.title)
            new_mat.save()

        return super().form_valid(form)


class BlogUpdateView(UpdateView):
    model = Post
    fields = ('title', 'description', 'image', 'is_published')
    extra_context = {
        'title': 'Update Post'
    }

    def form_valid(self, form):
        if form.is_valid():
            new_mat = form.save()
            new_mat.slug = slugify(new_mat.title)
            new_mat.save()

        return super().form_valid(form)

    def get_success_url(self):
        return reverse('blog:view', args=[self.object.pk])


class BlogListView(ListView):
    model = Post
    extra_context = {
        'title': 'Blog'
    }

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(is_published=True)
        return queryset


class BlogDetailView(DetailView):
    model = Post

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        post = self.get_object()
        post.views_count += 1
        post.save()
        context['title'] = post.title
        return context


class BlogDeleteView(DeleteView):
    model = Post
    success_url = reverse_lazy('blog:blog')
    extra_context = {
        'title': 'Delete Post'
    }

blog/templates/post_confirm_delete.html
{% extends 'catalog/basic.html' %}
{% block content %}
{% load custom %}
<div class="text-center container">
    <div class="col-12">
        <div class="row">
            <div class="card">
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        <p>Can yoy delete post: "{{ object.name }}"</p>
                        {% csrf_token %}
                        <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Delete</button>
                        <a type="button" href="{% url 'blog:blog'%}" class="btn btn-lg btn-block btn-outline-primary">return</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

blog/templates/post_detail.html
{% extends 'catalog/basic.html' %}
{% block content %}
{% load custom %}

<div class="col-12">
    <div class="text-center container">
        <div class="card shadow-sm" style="height: 24rem;">
            <img src="{% my_media_tag product.image %}" class="card-img-top mb-3" alt="...">
            <div class="card-body">
                <h5 class="card-title mb-3">{{ object.title|title }}</h5>
                <h6 class="card-subtitle mb-3 text-body-secondary">{{ object.slug }}</h6>
                <p class="card-text">{{ object.description }}</p>
                <div>
                    <a href="{% url 'blog:blog' %}" type="button"
                       class="btn btn-sm btn-outline-secondary mb-3">Back to blog</a>

                    <div class="row mb-3">
                        <a>
                            <small class="text-body-secondary">Created at {{ object.created_at }}</small>
                            <small class="text-body-secondary">Views count {{ object.views_count }}</small>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/post_form.html
{% extends 'catalog/basic.html' %}
{% block content %}
{% load custom %}
<div class="text-center container">
    <div class="col-12">
        <div class="row">
            <div class="card">
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-lg btn-block btn-outline-primary">
                            {% if object %}
                            Изменить
                            {% else %}
                            Отправить
                            {% endif %}
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

blog/templates/post_list.html
{% extends 'catalog/basic.html' %}
{% block content %}
{% load custom %}

<div class="text-center container">
<a class="btn btn-primary" href="{% url 'blog:create' %}" type="button">Create Post</a>
</div>

<div class="album py-5 bg-body-tertiary">
    <div class="text-center container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">

            {% for object in post_list %}

            <div class="col">
                <div class="card shadow-sm" style="height: 24rem;">
                    <img src="{% my_media_tag product.image %}" class="card-img-top" alt="...">
                    <div class="card-body">
                        <h5 class="card-title">{{ object.title|title }}</h5>
                        <p class="card-text">{{ object.description|truncatechars:100 }}</p>
                        <div>
                           <a href="{% url 'blog:view' object.pk %}" type="button"
                           class="btn btn-sm btn-outline-secondary">View</a>
                            <a href="{% url 'blog:edit' object.pk %}" type="button"
                           class="btn btn-sm btn-outline-secondary">Edit</a>
                            <a href="{% url 'blog:delete' object.pk %}" type="button"
                           class="btn btn-sm btn-outline-secondary">Delete</a>
                        </div>

                    </div>
                </div>
            </div>

            {% endfor %}


        </div>
    </div>
</div>

{% endblock %}