blog/urls.py
from django.urls import path
from django.contrib import admin
from blog.views import BlogListView, BlogCreateView, BlogDetailView, BlogUpdateView, BlogDeleteView
from blog.apps import BlogConfig
app_name = BlogConfig.name

urlpatterns = [
    path('create/', BlogCreateView.as_view(), name='create'),
    path('', BlogListView.as_view(), name='blog'),
    path('view/<int:pk>/', BlogDetailView.as_view(), name='view'),
    path('edit/<int:pk>/', BlogUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='delete'),
]

catalog/urls.py
from django.urls import path
from django.contrib import admin
from catalog.views import IndexListView, ContactsPageView, ProductDetailView, ProductCreateView, ProductUpdateView, \
    ProductDeleteView
from catalog.apps import CatalogConfig
from django.views.decorators.cache import cache_page

app_name = CatalogConfig.name

urlpatterns = [
    path('', IndexListView.as_view(), name='index'),
    path('contacts/', ContactsPageView.as_view(), name='contacts'),
    #path("product/<int:pk>/", ProductDetailView.as_view(), name="product-detail"),
    path('product/<int:pk>/', cache_page(30)(ProductDetailView.as_view()), name='product-detail'),
    path('create/', ProductCreateView.as_view(), name='create_product'),
    path('update/<int:pk>/', ProductUpdateView.as_view(), name='update_product'),
    path('delete/<int:pk>/', ProductDeleteView.as_view(), name='delete_product'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('catalog.urls', namespace='catalog')),
                  path('blog/', include('blog.urls', namespace='blog')),
                  path('users/', include('users.urls', namespace='users')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from django.contrib import admin
from users.apps import UsersConfig
from users.views import UserLogin, UserLogout, RegisterView, UserConfirmEmailView, UserConfirmedView, UserConfirmationFailView, generate_new_password, regenerate_password, UserConfirmationSentView

app_name = UsersConfig.name

urlpatterns = [
    path('login/', UserLogin.as_view(), name='login'),
    path('logout/', UserLogout.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('confirm_email/<str:uidb64>/<str:token>/', UserConfirmEmailView.as_view(), name='confirm_email'),
    path('email_confirmed/', UserConfirmedView.as_view(), name='email_confirmed'),
    path('email_confirmation_failed/', UserConfirmationFailView.as_view(), name='email_confirmation_failed'),
    path('profile/genpassword/', generate_new_password, name='generate_new_password'),
    path('regenerations/', regenerate_password, name='regenerate_password'),
    path('email_confirmation_sent/', UserConfirmationSentView.as_view(), name='email_confirmation_sent'),
]

catalog/models.py
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from config import settings
from django.conf import settings

NULLABLE = {'blank':  True, 'null': True}

# Create your models here.
class Product(models.Model):
    title = models.CharField(max_length=100, verbose_name= 'наименование')
    description = models.TextField(verbose_name= 'описание', **NULLABLE)
    preview = models.ImageField(upload_to='products/', verbose_name= 'изображение', **NULLABLE)
    category = models.ForeignKey(
        'catalog.Category',
        on_delete=models.CASCADE,
        verbose_name= 'категория',
    )
    price = models.PositiveIntegerField(verbose_name= 'цена за покупку')
    created = models.DateTimeField(
        auto_now_add=True,
        verbose_name='дата создания'
    )
    updated = models.DateTimeField(
        auto_now=True,
        verbose_name='дата последнего изменения'
    )

    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, verbose_name='владелец', **NULLABLE)
    is_published = models.BooleanField(default=False, verbose_name='статус публикации')

    def __str__(self):
        return f'{self.title} ({self.description}): {self.price}'

    class Meta:
        verbose_name = 'продукт'
        verbose_name_plural = 'продукты'


class Category(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField(**NULLABLE)

    def __str__(self):
        return f'{self.title}: {self.description}'

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'категории'
        ordering = ('title',)


class Version(models.Model):
    VERSION_CHOICES = ((True, 'активная'), (False, 'не активная'))

    product = models.ForeignKey(
        'catalog.Product',
        on_delete=models.CASCADE,
        verbose_name='Продукт'
    )
    version_number = models.IntegerField(default=1, blank=True, verbose_name='Номер версии')
    version_name = models.CharField(max_length=250, verbose_name='Название версии')
    is_current = models.BooleanField(choices=VERSION_CHOICES, verbose_name='Признак текущей версии')

    def __str__(self):
        return f'{self.product} {self.version_number}'

    class Meta:
        verbose_name = 'Версия'
        verbose_name_plural = 'Версии'
        ordering = ('version_number',)  # сортировка по номеру версии

catalog/forms.py
from django import forms
from catalog.models import Product, Version



class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class ProductForm(StyleFormMixin, forms.ModelForm):

    class Meta:
        model = Product
        #fields = '__all__'
        #fields = ('title', 'description')
        exclude = ('owner', )

    def clean_title(self):
        cleaned_data = self.cleaned_data['title']
        bad_words = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция', 'радар']
        for word in bad_words:
            if word in cleaned_data.lower():
                raise forms.ValidationError('В названии продукта используются запрещенные слова')
        return cleaned_data

    def clean_description(self):
        cleaned_data = self.cleaned_data['description']
        bad_words = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция', 'радар']
        for word in bad_words:
            if word in cleaned_data.lower():
                raise forms.ValidationError('В описании продукта используются запрещенные слова')
        return cleaned_data

class VersionForm(StyleFormMixin, forms.ModelForm):

    class Meta:
        model = Version
        fields = '__all__'

catalog/views.py
from django.shortcuts import render
from catalog.models import Product, Version
from django.http import HttpRequest, HttpResponse
from django.shortcuts import get_object_or_404
from django.views import View
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView
from catalog.forms import ProductForm, VersionForm
from django.urls import reverse_lazy
from django.forms import inlineformset_factory
from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import Http404
from catalog.services import get_category_cache
from django.core.cache import cache


# Create your views here.

# def index(request):
#     product_list = Product.objects.all()
#     context = {
#         'object_list' : product_list
#     }
#     return render(request, 'catalog/index.html', context)

class IndexListView(ListView):
    model = Product
    template_name = 'catalog/index.html'
    extra_context = {
        'title': 'index'
    }

    def get_context(self):
        context_data = get_category_cache()
        return context_data

    # def get_queryset(self, *args, **kwargs):
    #     queryset = super().get_queryset(*args, **kwargs)
    #     # queryset = queryset.filter(public_sign=True)
    #     return queryset

    def get_queryset(self):
        user = self.request.user

        if user.is_authenticated:  # для зарегистрированных пользователей
            if user.is_staff or user.is_superuser:  # для работников и суперпользователя
                queryset = super().get_queryset().order_by('pk')

            else:  # для остальных пользователей
                # Получаем queryset, результат фильтрации по условию owner=user
                queryset_1 = super().get_queryset().filter(owner=self.request.user).order_by('pk')
                # Получаем queryset, результат фильтрации по условию is_published=True
                queryset_2 = super().get_queryset().filter(is_published=True).order_by('pk')
                # Объединяем два queryset с использованием метода union()
                queryset = queryset_2.union(queryset_1)
                # queryset = super().get_queryset().filter(owner=user).order_by('pk')

        else:  # для незарегистрированных пользователей
            queryset = super().get_queryset().filter(
                is_published=True).order_by('-pk')

        return queryset




    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['version'] = Version.objects.all()
        return context


# def contacts(request):
#     if request.method == 'POST':
#         name = request.POST.get('name')
#         phone = request.POST.get('phone')
#         message = request.POST.get('message')
#         print(f'{name} ({email}): {message}')
#     return render(request, 'catalog/contacts.html')

class ContactsPageView(View):

    def get(self, request):
        context = {'title': 'Контакты'}
        return render(request, 'catalog/contacts.html', context)


    def post(self, request):
        name = request.POST.get('name')
        phone = request.POST.get('phone')
        message = request.POST.get('message')
        print(f'{name} ({email}): {message}')
        context = {'title': 'Контакты'}
        return render(request, 'catalog/contacts.html', context)


# def product_detail(request: HttpRequest, pk: int) -> HttpResponse:
#     product = get_object_or_404(Product, pk=pk)
#     ctx = {
#         "object": product
#     }
#     return render(request, template_name='catalog/product.html', context=ctx)

class ProductDetailView(View):

    def get(self, request, pk):
        product = Product.objects.get(id=pk)
        context = {
            'object': product,
            'title': f'{product.title}'
        }
        return render(request, 'catalog/product.html', context)


class ProductCreateView(CreateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog:index')
    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        return context_data


    def form_valid(self, form):
        self.object = form.save()
        self.object.owner = self.request.user
        self.object.save()

        return super().form_valid(form)



class ProductUpdateView(UpdateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog:index')


    def get_form_class(self):
        return super().get_form_class()


    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        VersionFormset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)
        if self.request.method == 'POST':
            context_data['formset'] = VersionFormset(self.request.POST, instance=self.object)
        else:
            context_data['formset'] = VersionFormset(instance=self.object)
        return context_data


    def form_valid(self, form):
        context_data = self.get_context_data()
        formset = context_data['formset']
        self.object = form.save()

        if formset.is_valid():
            formset.instance = self.object
            formset.save()

        return super().form_valid(form)


    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.object.owner != self.request.user and not self.request.user.is_staff:
            raise Http404("Вы не являетесь владельцем этого товара")
        return self.object


    def test_func(self):
        _user = self.request.user
        _instance: Product = self.get_object()
        custom_perms: tuple = (
            'catalog_app.set_is_published',
            'catalog_app.set_category',
            'catalog_app.set_description',
        )

        if _user == _instance.user:
            return True
        elif _user.groups.filter(name='moders') and _user.has_perms(custom_perms):
            return True
        return self.handle_no_permission()



class ProductDeleteView(LoginRequiredMixin, DeleteView):
    model = Product
    success_url = reverse_lazy('catalog:index')

catalog/templates/catalog/base.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="/docs/4.0/assets/img/favicons/favicon.ico">

    <title>Carousel Template for Bootstrap</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css'%}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/carousel.css' %}" rel="stylesheet">
</head>
<body>

<header>
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <a class="navbar-brand" href="{% url 'catalog:index' %}">Home</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
                aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'catalog:contacts' %}">Contacts <span
                            class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'blog:blog' %}">Blog <span class="sr-only">(current)</span></a>
                </li>
            </ul>
            <ul class="navbar-nav mr-auto">
                {% if not user.is_authenticated %}
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'users:login' %}">Вход <span
                            class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'users:register' %}">Регистрация <span
                            class="sr-only">(current)</span></a>
                </li>

                {% else %}

                <li class="nav-item active">
                    <a class="nav-link" href="">Профиль <span
                            class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'users:logout' %}">Выход <span
                            class="sr-only">(current)</span></a>
                </li>
                {% endif %}

            </ul>
            <!--            <form class="form-inline mt-2 mt-md-0">-->
            <!--                <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">-->
            <!--                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>-->
            <!--            </form>-->
        </div>
    </nav>
</header>

<main role="main">

    <div id="myCarousel" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
            <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
            <li data-target="#myCarousel" data-slide-to="1"></li>
            <li data-target="#myCarousel" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner">
            <!--            <div class="carousel-item active">-->
            <!--                <img class="first-slide"-->
            <!--                     src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw=="-->
            <!--                     alt="First slide">-->
            <!--                <div class="container">-->
            <!--                    <div class="carousel-caption text-left">-->
            <!--                        <h1>Example headline.</h1>-->
            <!--                        <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta-->
            <!--                            gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>-->
            <!--                        <p><a class="btn btn-lg btn-primary" href="#" role="button">Sign up today</a></p>-->
            <!--                    </div>-->
            <!--                </div>-->
            <!--            </div>-->
            <!--            <div class="carousel-item">-->
            <!--                <img class="second-slide"-->
            <!--                     src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw=="-->
            <!--                     alt="Second slide">-->
            <!--                <div class="container">-->
            <!--                    <div class="carousel-caption">-->
            <!--                        <h1>Another example headline.</h1>-->
            <!--                        <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta-->
            <!--                            gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>-->
            <!--                        <p><a class="btn btn-lg btn-primary" href="#" role="button">Learn more</a></p>-->
            <!--                    </div>-->
            <!--                </div>-->
            <!--            </div>-->
            <!--            <div class="carousel-item">-->
            <!--                <img class="third-slide"-->
            <!--                     src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw=="-->
            <!--                     alt="Third slide">-->
            <!--                <div class="container">-->
            <!--                    <div class="carousel-caption text-right">-->
            <!--                        <h1>One more for good measure.</h1>-->
            <!--                        <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta-->
            <!--                            gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>-->
            <!--                        <p><a class="btn btn-lg btn-primary" href="#" role="button">Browse gallery</a></p>-->
            <!--                    </div>-->
            <!--                </div>-->
            <!--            </div>-->
        </div>
        <!--        <a class="carousel-control-prev" href="#myCarousel" role="button" data-slide="prev">-->
        <!--            <span class="carousel-control-prev-icon" aria-hidden="true"></span>-->
        <!--            <span class="sr-only">Previous</span>-->
        <!--        </a>-->
        <!--        <a class="carousel-control-next" href="#myCarousel" role="button" data-slide="next">-->
        <!--            <span class="carousel-control-next-icon" aria-hidden="true"></span>-->
        <!--            <span class="sr-only">Next</span>-->
        <!--        </a>-->
    </div>

    {% block content %}
    {% endblock %}


    <!-- FOOTER -->
    <footer class="container">
        <p class="float-right"><a href="#">Back to top</a></p>
        <p>&copy; 2023 - {% now 'Y' %}</p>
    </footer>
</main>

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="{% static 'js/slim.min.js' %}"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script>window.jQuery || document.write('<script src="{% static 'js/jquery-slim.min.js' %}"><\/script>')</script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js'%}"></script>
<!-- Just to make our placeholder images work. Don't actually copy the next line! -->
<script src="{% static 'js/holder.min.js' %}"></script>
</body>
</html>

catalog/templates/catalog/contacts.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Skystore</title>
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">Skystore</h5>
    <nav class="ms-5">
        <a class="p-2 btn btn-outline-primary" href="/">Каталог</a>
        <a class="p-2 btn btn-outline-primary" href="/contacts/">Контакты</a>
    </nav>
</div>

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Контакты</h1>
</div>

<div class="container">
    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Страна</td>
                            <td>USA</td>
                        </tr>
                        <tr>
                            <td class="w-25">ИНН</td>
                            <td>91-1144442</td>
                        </tr>
                        <tr>
                            <td class="w-25">Адрес</td>
                            <td>Redmond,WA,98052-6399</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя" required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" class="form-control" id="phone" placeholder="Контактный телефон" required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea type="text" name="message" class="form-control" id="message" placeholder="Контактный телефон" required></textarea>
                        </div>
                    </form>
                    <input type="submit", value="Отправить"/>
                </div>
            </div>
        </div>
    </div>

    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                SkyStore
                <small class="d-block mb-3 text-muted">&copy; 2023</small>
            </div>
            <div class="col-6 col-md">
                <h5>Категории</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Рассылки</a></li>
                    <li><a class="text-muted" href="#">Телеграм боты</a></li>
                    <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                    <li><a class="text-muted" href="#">Веб-приложения</a></li>
                    <li><a class="text-muted" href="#">Микросервисы</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Мы пишем</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="/contacts/">Контакты</a></li>
                </ul>
            </div>
        </div>
    </footer>
</div>

<script src="/static/js/bootstrap.bundle.min.js"></script>
</body>
</html>

catalog/templates/catalog/index.html
{% extends 'catalog/base.html' %}
{% load custom %}
{% block content %}
<div class="container marketing">
    <!-- Three columns of text below the carousel -->
    {% if user.is_authenticated %}
    <div class="col-12 mb-5">
        <a class="p-2 btn btn-success"
           href="{% url 'catalog:create_product' %}">+Добавить товар</a>
    </div>
    {% endif %}
    <div class="row">
        {% for object in object_list %}
        {% if object.is_published %}
        <div class="col-lg-4">
            <img class="rounded-circle"
                 src="{% mediapath object.preview %}"
                 alt="Generic placeholder image"
                 width="140" height="140">
            <h2>{{ object.title | title }}</h2>
            <h4>{{ object.price }} руб.</h4>
            <p>{{ object.description | truncatechars:100 }}</p>

            {% if object.owner %}
                владелец - {{ object.owner }}
            {% else %}
            владелец - нет
                {% endif %}


            <div class="card-body">
                {% for version in object.version_set.all %}
                {% if version.is_current %}
                версия - {{ version.version_number }}
                {% endif %}
                {% endfor %}
            </div>

            <a class="p-2 btn btn-info"
               href="{% url 'catalog:product-detail' object.pk %}">Подробнее</a>
            {% if perms.catalog.delete_product %}
            <a class="p-2 btn btn-warning"
               href="{% url 'catalog:update_product' object.pk %}">Изменить</a>

            <a class="p-2 btn btn-danger"
               href="{% url 'catalog:delete_product' object.pk %}">Удалить</a>
            {% endif %}

        </div>
{% endif %}
        {% endfor %}
    </div><!-- /.row -->
</div><!-- /.container -->

{% endblock %}

catalog/templates/catalog/product.html
{% extends 'catalog/base.html' %}
{% load custom %}

{% block title %}{{ object.name }}{% endblock %}

{% block content %}
<section class="py-5">
    <div class="container px-4 px-lg-5 my-5">
        <div class="row gx-4 gx-lg-5 align-items-center">
            {% if not object.preview %}
            <div class="col-md-6"><img class="card-img-top mb-5 mb-md-0"
                                       src="https://dummyimage.com/600x700/dee2e6/6c757d.jpg" alt="..."/></div>
            {% else %}
            <div class="col-md-6"><img class="card-img-top mb-5 mb-md-0" src="{% mediapath object.preview %}"
                                       alt="..."/></div>
            {% endif %}
            <div class="col-md-6">
                <div class="small mb-1">Категория: {{ object.category }}</div>
                <h1 class="display-5 fw-bolder">{{ object.title }}</h1>
                <div class="fs-5 mb-5">
                    {# <span class="text-decoration-line-through">$45.00</span>#}
                    <span>₽{{ object.price }}</span>
                </div>
                <div class="small mb-1">{{ object.created_at }}</div>
                <p class="lead">{{ object.description }}</p>
                <div class="card-body">
                    {% for version in object.version_set.all %}
                    {% if version.is_current %}
                    версия - {{ version.version_number }}
                    {% endif %}
                    {% endfor %}
                </div>
                <div class="d-flex">
                    <input class="form-control text-center me-3" id="inputQuantity" type="num" value="1"
                           style="max-width: 3rem"/>
                    <button class="btn btn-outline-dark flex-shrink-0" type="button">
                        <i class="bi-cart-fill me-1"></i>
                        Добавить в корзину
                    </button>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

catalog/templates/catalog/product_confirm_delete.html
{% extends 'catalog/base.html' %}
{% block content %}
{% load custom %}
<div class="text-center container">
    <div class="col-12">
        <div class="row">
            <div class="card">
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        <p>Удаление продукта</p>
                        {% csrf_token %}
                        <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Удалить</button>
                        <a type="button" href="{% url 'catalog:index'%}" class="btn btn-lg btn-block btn-outline-primary">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

catalog/templates/catalog/product_form.html
{% extends 'catalog/base.html' %}
{% block content %}

<div class="col-6">
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">
                Добавление товара
            </h3>
        </div>
        <div class="card-body">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{form.as_p}}
                <button type="submit" class="btn btn-success">Сохранить</button>
        </div>


        <div class="footer"></div>
    </div>
</div>
<div class="col-6">
    <div class="card">
        <div class="card-header">
            Версия
        </div>
        <div class="card-body">
            {{ formset.management_form }}
            {% for form in formset.forms %}
            {{form.as_p}}
            {% endfor %}
        </div>
    </div>
</div>
</form>
{% endblock %}